FROM alpine:3

LABEL author="Pyari Visvapujita Devi Dasi"
LABEL nim="2305551069" website="https://www.mjs-kelas-b.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"
